## Content-Based Filtering

In [1]:
import pandas
movies = pandas.read_csv("movies.csv", sep=",")

In [2]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words="english")
movies["overview"] = movies["overview"].fillna("")

In [4]:
tfidf_matrix = tfidf.fit_transform(movies["overview"])

In [5]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 125840 stored elements and shape (4803, 20978)>

In [6]:
pandas.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zuckerberg,zula,zuzu,zyklon,æon,éloigne,émigré,été,única,über
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [7]:
tfidf_matrix.shape

(4803, 20978)

In [8]:
movies["overview"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: str

## Similarity matrix

In [9]:
from sklearn.metrics.pairwise import linear_kernel
similarity_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [10]:
similarity_matrix

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02160533, 0.01488159, ..., 1.        , 0.01609091,
        0.00701914],
       [0.        , 0.        , 0.        , ..., 0.01609091, 1.        ,
        0.01171696],
       [0.        , 0.        , 0.        , ..., 0.00701914, 0.01171696,
        1.        ]], shape=(4803, 4803))

In [11]:
similarity_matrix[0]

array([1., 0., 0., ..., 0., 0., 0.], shape=(4803,))

In [12]:
similarity_matrix[1]

array([0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
       0.        ], shape=(4803,))

## Find the most similar movies to a certain movie

In [13]:
movie_title = "John Carter"

In [14]:
idx = movies.loc[movies["title"]==movie_title].index[0]
idx

4

#### The key parameter tells sorted() to use the second element [1] of each (index, score) tuple
#### as the sorting criterion. The lambda function extracts the score value for comparison.
#### reverse=True orders from highest to lowest similarity

In [15]:
scores = list(enumerate(similarity_matrix[idx]))
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.033368675996424305)),
 (2, np.float64(0.0)),
 (3, np.float64(0.010433403719159353)),
 (4, np.float64(1.0)),
 (5, np.float64(0.0)),
 (6, np.float64(0.009339192776152498)),
 (7, np.float64(0.037407042075763064)),
 (8, np.float64(0.0)),
 (9, np.float64(0.01714819056424443)),
 (10, np.float64(0.02015372184154536)),
 (11, np.float64(0.0)),
 (12, np.float64(0.03178129553727139)),
 (13, np.float64(0.0)),
 (14, np.float64(0.010712515993695904)),
 (15, np.float64(0.0)),
 (16, np.float64(0.045257098111540495)),
 (17, np.float64(0.020358841382635908)),
 (18, np.float64(0.016907757517459005)),
 (19, np.float64(0.016254574057966483)),
 (20, np.float64(0.00914487577692374)),
 (21, np.float64(0.01727519014981104)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.01651050909357743)),
 (25, np.float64(0.0)),
 (26, np.float64(0.05387465159298631)),
 (27, np.float64(0.05231039324590807)),
 (28, np.float64(0.025467489988822038)),
 (29, np.float64

In [16]:
sorted(scores, key=lambda x: x[1], reverse=True)

[(4, np.float64(1.0)),
 (1254, np.float64(0.20497253140891997)),
 (4161, np.float64(0.16370347641323713)),
 (2932, np.float64(0.12239400129620456)),
 (3349, np.float64(0.1188715104057236)),
 (1307, np.float64(0.11468689553107403)),
 (3068, np.float64(0.11237609168095009)),
 (345, np.float64(0.09079218287485014)),
 (581, np.float64(0.0900594125581888)),
 (2998, np.float64(0.08877535757173034)),
 (4274, np.float64(0.08576462030578072)),
 (46, np.float64(0.08574401380341932)),
 (1735, np.float64(0.08506583325352486)),
 (2755, np.float64(0.08374900580033416)),
 (2968, np.float64(0.08283973259290776)),
 (1057, np.float64(0.07986162067710445)),
 (85, np.float64(0.07927219338261442)),
 (322, np.float64(0.07826834318581481)),
 (1300, np.float64(0.0775741581048838)),
 (2300, np.float64(0.07715566889765219)),
 (2155, np.float64(0.07713065113739949)),
 (2417, np.float64(0.07556384384487905)),
 (694, np.float64(0.07473047732188678)),
 (2265, np.float64(0.0714410805050381)),
 (373, np.float64(0.071

#### Convert the NumPy array of similarity scores to a native Python list
#### The tolist() method transforms each np.float64 element into a standard float,
#### allowing sorted() to return clean numeric values without the NumPy type wrapper

In [17]:
sorted(similarity_matrix[5].tolist(), reverse=True)

[0.9999999999999998,
 0.28269377551691705,
 0.24647209184826266,
 0.23671046045214342,
 0.22284657494531743,
 0.21139629084201758,
 0.17166864148468533,
 0.10119023772910764,
 0.09698331013627293,
 0.09441228946181329,
 0.09420458163538704,
 0.09387869751025701,
 0.093179656021935,
 0.09294607512398585,
 0.08922096637425693,
 0.08822773156402856,
 0.08703321890643594,
 0.08655694622282886,
 0.07939905109264418,
 0.07824238152983498,
 0.0771307649186758,
 0.0770514400121716,
 0.07666361494130405,
 0.07553757363470058,
 0.07361132574539064,
 0.0730490466716229,
 0.07284646449723593,
 0.07255069266221406,
 0.07217331418966348,
 0.07214356973032558,
 0.06945848378728416,
 0.06936893001217233,
 0.06881212373296748,
 0.06876117376909216,
 0.06775861287012117,
 0.06714323008705704,
 0.06666577399021334,
 0.06635302952940192,
 0.06622358568674479,
 0.06578785204496,
 0.06511642814091788,
 0.064350600201051,
 0.06402613885361341,
 0.06371822899573716,
 0.06353750224737026,
 0.06242336147120036,

In [18]:
scores

[(0, np.float64(0.0)),
 (1, np.float64(0.033368675996424305)),
 (2, np.float64(0.0)),
 (3, np.float64(0.010433403719159353)),
 (4, np.float64(1.0)),
 (5, np.float64(0.0)),
 (6, np.float64(0.009339192776152498)),
 (7, np.float64(0.037407042075763064)),
 (8, np.float64(0.0)),
 (9, np.float64(0.01714819056424443)),
 (10, np.float64(0.02015372184154536)),
 (11, np.float64(0.0)),
 (12, np.float64(0.03178129553727139)),
 (13, np.float64(0.0)),
 (14, np.float64(0.010712515993695904)),
 (15, np.float64(0.0)),
 (16, np.float64(0.045257098111540495)),
 (17, np.float64(0.020358841382635908)),
 (18, np.float64(0.016907757517459005)),
 (19, np.float64(0.016254574057966483)),
 (20, np.float64(0.00914487577692374)),
 (21, np.float64(0.01727519014981104)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.01651050909357743)),
 (25, np.float64(0.0)),
 (26, np.float64(0.05387465159298631)),
 (27, np.float64(0.05231039324590807)),
 (28, np.float64(0.025467489988822038)),
 (29, np.float64

In [19]:
movies_indices = [tpl[0] for tpl in scores[1:4]]
movies_indices

[1, 2, 3]

In [20]:
list(movies["title"].iloc[movies_indices])

["Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises']

In [21]:
def similar_movies(movies_title, nr_movies):
    idx = movies.loc[movies["title"]==movies_title].index[0]
    scores = list(enumerate(similarity_matrix[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    movies_indices = [tpl[0] for tpl in scores[1:nr_movies+1]]
    similar_titles = list(movies["title"].iloc[movies_indices])
    return similar_titles

In [22]:
similar_movies("Kung Fu Panda 3", 3)

['Kung Fu Panda 2',
 'My Big Fat Greek Wedding 2',
 'Once Upon a Time in the West']